🧪 73 add domain unit tests (#75)
* Updated readme

* Moved application into src directory

* Added customer unit tests

* Added product tests

* Added money unit tests

* Added Sku unit tests

* Added Order unit tests

* Build now runs tests

* Fixed warnings

* Update action permissions

* Tidied up permission check

* Added build badge

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -9,9 +9,11 @@ on:
   pull_request:
     branches: [ "main" ]
 
+permissions:
+  checks: write
+
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
@@ -22,5 +24,12 @@ jobs:
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore -c Release -warnaserror
-    #- name: Test
-    #  run: dotnet test --no-build --verbosity normal
+    - name: Test
+      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=TestResults.trx"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: tests             # Name of the check run which will be created
+        path: "**/*.trx"        # Path to test results
+        reporter: dotnet-trx    # Format of test results
